---
- name: Show Specific CV Version Infomation
  hosts: all
  gather_facts: false

  tasks:
  - name: Show CV info
    redhat.satellite.content_view_version_info:
      server_url: "{{ satellite_url }}"
      username: "{{ satellite_user }}"
      password: "{{ satellite_password }}"
      content_view: "CV-RHEL2"
      validate_certs: false
      organization: "home_lab"
    register: content_view 

  - name: Collect all content view information
    redhat.satellite.host_info:
      server_url: "{{ satellite_url }}"
      username: "{{ satellite_user }}"
      password: "{{ satellite_password }}"
      name: "{{ host_name }}"
      validate_certs: false
      organization: "home_lab"
    register: content_view_host

  - name: Display content view host info
    ansible.builtin.debug:
      msg: "{{ content_view_host.host.certname }} is Ver {{ content_view_host.host.content_facet_attributes.content_view_version }}"
      
  - name: Display content view version info
    ansible.builtin.debug:
      msg:
      - "{{ content_view.content_view_versions[3].name }} は {{ content_view.content_view_versions[3].description }} "
      - "{{ content_view.content_view_versions[2].name }} は {{ content_view.content_view_versions[2].description }} "
      - "{{ content_view.content_view_versions[1].name }} は {{ content_view.content_view_versions[1].description }} "
      - "{{ content_view.content_view_versions[0].name }} は {{ content_view.content_view_versions[0].description }} "
#      var: content_view.host.content_facet_attributes.content_view_environments
#      var: content_view.content_view_versions[0]
