---
- name: Confirm the specific content view infomation
  hosts: all
  gather_facts: false

  tasks:
  - name: Collect all content view information
    redhat.satellite.host_info:
      server_url: "{{ satellite_url }}"
      username: "{{ satellite_user }}"
      password: "{{ satellite_password }}"
      name: "rhel91-dev.lab.local"
      validate_certs: false
      organization: "home_lab"
    register: content_view 

  - name: Display content view information
    ansible.builtin.debug:
      msg: "このサーバーのコンテンツビューのバージョンは、{{ content_view.host.content_facet_attributes.content_view_version }} です"
#      var: content_view.host.content_facet_attributes.content_view_environments
#      var: content_view
