---
- name: Show Specific CV Version Infomation
  hosts: all
  gather_facts: false

  tasks:
  - name: Show CV info
    redhat.satellite.content_view_version_info:
      server_url: "{{ satellite_url }}"
      username: "{{ satellite_user }}"
      password: "{{ satellite_password }}"
      content_view: "CV-RHEL"
      validate_certs: false
      organization: "home_lab"
    register: content_view 

  - name: Display content view information
    ansible.builtin.debug:
      msg: "{{ content_view.content_view_versions[0].name }} は {{ ontent_view.content_view_versions[0].description }} です。"
      msg: "{{ content_view.content_view_versions[1].name }} は {{ ontent_view.content_view_versions[1].description }} です。"
      msg: "{{ content_view.content_view_versions[2].name }} は {{ ontent_view.content_view_versions[2].description }} です。"
      msg: "{{ content_view.content_view_versions[3].name }} は {{ ontent_view.content_view_versions[3].description }} です。"
#      var: content_view.host.content_facet_attributes.content_view_environments
#      var: content_view.content_view_versions[0]
