---
- name: Show Specific CV Version Infomation
  hosts: all
  gather_facts: false
  
  tasks:
  - name: Create content view
    redhat.satellite.content_view:
      server_url: "{{ satellite_url }}"
      username: "{{ satellite_user }}"
      password: "{{ satellite_password }}"    
      validate_certs: false
      name: "CV-RHEL2"
      organization: "home_lab"
#      auto_publish: true
      description: "for Demo"
      repositories:
        - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9'
          product: 'Red Hat Enterprise Linux for x86_64'
        - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9'
          product: 'Red Hat Enterprise Linux for x86_64'
