---
- name: Publish Satellite CV New Version with Filter (Issue Date)
  hosts: all
  gather_facts: false

  tasks:
#  - name: Create content view filter
#    redhat.satellite.content_view_filter:
#      server_url: "{{ satellite_url }}"
#      username: "{{ satellite_user }}"
#      password: "{{ satellite_password }}"
#      validate_certs: false
#      content_view: "{{ content_view }}"
#      organization: "home_lab"
#      name: "{{ filter_name }}"
#      description: "{{ comment }}"
#      filter_type: erratum
#      inclusion: true

  - name: Configurate content view filter rule
    redhat.satellite.content_view_filter_rule:
      server_url: "{{ satellite_url }}"
      username: "{{ satellite_user }}"
      password: "{{ satellite_password }}"    
      validate_certs: false
      content_view: "{{ content_view }}"
      organization: "home_lab"
      content_view_filter: "{{ filter_name }}"
      name: "{{ filter_name }}"
      errata_id: "{{ errata_id }}"

#  - name: Publish New Version
#    redhat.satellite.content_view_version:
#      server_url: "{{ satellite_url }}"
#      username: "{{ satellite_user }}"
#      password: "{{ satellite_password }}"    
#      validate_certs: false
#      description: "{{ comment_eng }}"
#      content_view: "{{ content_view }}"
#      organization: "home_lab"

#  - name: Remove content view filter
#    redhat.satellite.content_view_filter:
#      server_url: "{{ satellite_url }}"
#      username: "{{ satellite_user }}"
#      password: "{{ satellite_password }}"    
#      validate_certs: false
#      content_view: "{{ content_view }}"
#      organization: "home_lab"
#      filter_type: erratum
#      name: "{{ filter_name }}"
#      filter_state: absent
