---
- name: Promote Content view
  hosts: all
  gather_facts: false

  tasks:
  - name: Manage content view
    redhat.satellite.content_view_version:
      server_url: "{{ satellite_url }}"
      username: "{{ satellite_user }}"
#      password: "{{lookup('env', 'SATELLITE_PASSWORD')}}"
      password: "{{ satellite_password }}"    
      content_view: "CV-RHEL"
      organization: "home_lab"
      version: "{{ cv_version }}"
      force_promote: true
      validate_certs: false
      lifecycle_environments:
#        - Library
        - Develop
