---
- name: Manage Content view
  hosts: all

  tasks:
  - name: 
    redhat.satellite.content_view_version:
    content_view: "CV-RHEL"
    organization: "home_lab"
    version: "18.0"
    lifecycle_environments:
      - Library
      - Develop
