---
- name: Promote Content view
  hosts: all
  gather_facts: false

  tasks:
  - name: Manage content view
    redhat.satellite.content_view_version:
      server_url: https://192.168.21.228
      username: hokano
      password: "{{ password }}"    
      content_view: "CV-RHEL"
      organization: "home_lab"
      version: "9.0"
      validate_certs: false
      lifecycle_environments:
        - Library
        - Develop
