---
- name: Publish Satellite CV New Version with Filter (Issue Date)
  hosts: all
  gather_facts: false

  pre_tasks:
  - name: Publish content view filter
    redhat.satellite.content_view_version:
      server_url: "{{ satellite_url }}"
      username: "{{ satellite_user }}"
      password: "{{ satellite_password }}"    
      validate_certs: false
      description: "RHEL 9.1 First Release(2022-11-14)"
      content_view: "CV-RHEL2"
      organization: "home_lab"
