---
- name: Create Snapshot VM by using vmrun command 
  hosts: all
  tasks: 
    - name: take snapshot
      ansible.windows.win_command: '"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" snapshot F:\VM\tt\tt.vmx backups'
#      ansible.windows.win_command: '"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" listsnapshots F:\VM\tt\tt.vmx'
#      ansible.windows.win_command: 'C:\ansible\snapshot.bat'
#      ansible.windows.win_shell: C:\ansible\shapshot.ps1
#        no_profile: true
