---
- name: Create Snapshot VM by using vmrun command 
  hosts: all
  tasks: 
    - name: take snapshot
#      ansible.windows.win_command: '"C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe" snapshot F:\VM\RHEL9.1-1\RHEL9.1-1.vmx backups'
#      ansible.windows.win_command: 'C:\ansible\snapshot.bat'
      ansible.windows.win_shell: C:\ansible\snapshot.ps1 > result.txt
